### ISSUE TITLE
add crti.o

### ISSUE THREAD

**Issue by Tealk** [peaceiris/docker-mdbook#112]
Hello,

would it be possible to insert the image crti.o, then it would be immediately usable without modifications for https://github.com/tommilligan/mdbook-admonish.

https://codeberg.org/ButterflyAspect/mdBook/src/branch/develop/.woodpecker.yml#L41

https://ci.codeberg.org/repos/12296/pipeline/143/3#L355

**Comment by peaceiris** [comment]
Hi, could you try the latest image? `peaceiris/mdbook:v0.4.40`

**Comment by Tealk** [comment]
yes works, great <3

https://ci.codeberg.org/repos/12296/pipeline/148/3
