### ISSUE TITLE
Check for broken links

### ISSUE THREAD

**Issue by xoac** [peaceiris/docker-mdbook#2]
Hi

Thanks for awesome work. I am using this on my CI it would be nice to first test if links are correct before deploy. It could be part of `mdbook-<VERSION>-rust` similar like `mdbook test`. Links check can be done with [mdbook-linkcheck](https://github.com/Michael-F-Bryan/mdbook-linkcheck)

_there are also additional backends: https://rust-lang.github.io/mdBook/for_developers/backends.html_

**Comment by peaceiris** [comment]
That's interesting. I will add it.

Related: https://github.com/rust-lang/mdBook/issues/356

**Comment by peaceiris** [comment]
I have tried to install `mdbook-linkcheck`, it has some problems for installation.

Please wait for implementing the link check feature to mdBook.
 https://github.com/rust-lang/mdBook/issues/356

Or, use the other link check tools.
